// Store-related action types
export const STORE_FETCH_REQUEST = 'STORE_FETCH_REQUEST';
export const STORE_FETCH_SUCCESS = 'STORE_FETCH_SUCCESS';
export const STORE_FETCH_FAILURE = 'STORE_FETCH_FAILURE';

// Product-related action types
export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
export const PRODUCT_FETCH_FAILURE = 'PRODUCT_FETCH_FAILURE';

// Seller-specific product fetching
export const SELLER_PRODUCTS_FETCH_REQUEST = 'SELLER_PRODUCTS_FETCH_REQUEST';
export const SELLER_PRODUCTS_FETCH_SUCCESS = 'SELLER_PRODUCTS_FETCH_SUCCESS';
export const SELLER_PRODUCTS_FETCH_FAILURE = 'SELLER_PRODUCTS_FETCH_FAILURE';

export const ORDER_COUNTS_REQUEST = "ORDER_COUNTS_REQUEST";
export const ORDER_COUNTS_SUCCESS = "ORDER_COUNTS_SUCCESS";
export const ORDER_COUNTS_FAILURE = "ORDER_COUNTS_FAILURE";

export const FETCH_STORE_DETAILS_REQUEST = 'FETCH_STORE_DETAILS_REQUEST';
export const FETCH_STORE_DETAILS_SUCCESS = 'FETCH_STORE_DETAILS_SUCCESS';
export const FETCH_STORE_DETAILS_FAILURE = 'FETCH_STORE_DETAILS_FAILURE';

export const SELLER_ALL_PRODUCTS_FETCH_REQUEST = 'SELLER_ALL_PRODUCTS_FETCH_REQUEST';
export const SELLER_ALL_PRODUCTS_FETCH_SUCCESS = 'SELLER_ALL_PRODUCTS_FETCH_SUCCESS';
export const SELLER_ALL_PRODUCTS_FETCH_FAILURE = 'SELLER_ALL_PRODUCTS_FETCH_FAILURE';