// cartActionTypes.js
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILURE = "UPDATE_CART_FAILURE";

export const CLEAR_CART = "CLEAR_CART";

export const SET_GUEST_CART_ITEMS = 'SET_GUEST_CART_ITEMS';
export const UPDATE_GUEST_CART_ITEM = 'UPDATE_GUEST_CART_ITEM';
export const CLEAR_GUEST_CART = 'CLEAR_GUEST_CART';

export const CART_FLAG_TOGGLE = "CART_FLAG_TOGGLE"
