// Follow Store
export const FOLLOW_STORE_REQUEST = "FOLLOW_STORE_REQUEST";
export const FOLLOW_STORE_SUCCESS = "FOLLOW_STORE_SUCCESS";
export const FOLLOW_STORE_FAIL = "FOLLOW_STORE_FAIL";

// Fetch Followed Shops
export const FETCH_FOLLOWED_SHOPS_REQUEST = "FETCH_FOLLOWED_SHOPS_REQUEST";
export const FETCH_FOLLOWED_SHOPS_SUCCESS = "FETCH_FOLLOWED_SHOPS_SUCCESS";
export const FETCH_FOLLOWED_SHOPS_FAIL = "FETCH_FOLLOWED_SHOPS_FAIL";
