export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";

export const FETCH_ALLPRODUCT_REQUEST = "FETCH_ALLPRODUCT_REQUEST";
export const FETCH_ALLPRODUCT_SUCCESS = "FETCH_ALLPRODUCT_SUCCESS";
export const FETCH_ALLPRODUCT_FAILURE = "FETCH_ALLPRODUCT_FAILURE";