
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL';

export const GUEST_CHECKOUT_REQUEST = 'GUEST_CHECKOUT_REQUEST';
export const GUEST_CHECKOUT_SUCCESS = 'GUEST_CHECKOUT_SUCCESS';
export const GUEST_CHECKOUT_FAIL = 'GUEST_CHECKOUT_FAIL';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const FETCH_SELLER_ORDERS_REQUEST = 'FETCH_SELLER_ORDERS_REQUEST';
export const FETCH_SELLER_ORDERS_SUCCESS = 'FETCH_SELLER_ORDERS_SUCCESS';
export const FETCH_SELLER_ORDERS_FAILURE = 'FETCH_SELLER_ORDERS_FAILURE';